catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground
  - docs
  - packages/*
  - examples/*
overrides:
  '@noble/ed25519': ^2.0.0
  '@solana/web3.js': $@solana/web3.js
  axios: '>=0.30.0'
  form-data: '>=4.0.4'
  js-yaml: '>=4.1.1'
  nanoid: '>=3.3.8'

catalog:
  '@coral-xyz/anchor-29': npm:@coral-xyz/anchor@0.29.0
  '@coral-xyz/anchor-32': npm:@coral-xyz/anchor@0.32.0
  '@drift-labs/sdk': 2.155.0-beta.5
  '@drift-labs/vaults-sdk': 0.9.264
  '@solana/web3.js': ^1.98.4
  dotenv: ^17.2.3
  typedoc: ^0.28.16
  zod: ^4.3.5

catalogs:
  cli:
    '@antfu/eslint-config': ^6.6.1
    '@antfu/ni': ^28.0.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    publint: ^0.3.16
    simple-git-hooks: ^2.13.1
    tsdown: ^0.17.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.2.7
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.15
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

trustedDependencies:
  - '@noble/ed25519'
