// Generated by codama.mjs — do not edit.
// Anchor IDL for the ntbundle program, snapshotted at client generation time.
import ntbundleIdl from "./ntbundle.json";

export const NTBUNDLE_IDL = ntbundleIdl;
export default ntbundleIdl;
