import type { VaultConfig } from '../types'
import { SupportedToken, VaultId, VaultType } from '../types'

export const drift_vaults: Partial<Record<VaultId, VaultConfig>> = {
  [VaultId.jlpdnv1]: {
    vaultId: VaultId.jlpdnv1,
    name: 'JLP Delta Neutral',
    subname: 'vault-1',
    type: VaultType.Drift,
    vaultAddress: '3Nkctq19AW7gs5hkxixUDjS9UVjmCwcNCo7rqPpub87c',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
    driftProgramId: '9Fcn3Fd4d5ocrb12xCUtEvezxcjFEAyHBPfrZDiPt9Qj',
  },
  [VaultId.solnl]: {
    vaultId: VaultId.solnl,
    name: 'SOL Super Staking',

    type: VaultType.Drift,
    vaultAddress: 'EuSLjg23BrtwYAk1t4TFe5ArYSXCVXLBqrHRBfWQiTeJ',
    depositToken: SupportedToken.SOL,
    pfee: 0.2,
  },
  [VaultId.rekt]: {
    vaultId: VaultId.rekt,
    name: 'JLP Traders Rekt',

    type: VaultType.Drift,
    vaultAddress: '2r81MPMDjGSrbmGRwzDg6aqhe3t3vbKcrYfpes5bXckS',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.btcnl]: {
    vaultId: VaultId.btcnl,
    name: 'BTC Super Staking',

    type: VaultType.Drift,
    vaultAddress: 'BVddkVtFJLCihbVrtLo8e3iEd9NftuLunaznAxFFW8vf',
    depositToken: SupportedToken.WBTC,
    pfee: 0.2,
  },
  [VaultId.jlpdnv2]: {
    vaultId: VaultId.jlpdnv2,
    name: 'JLP Delta Neutral',
    subname: 'Drift-2',
    type: VaultType.Drift,
    vaultAddress: '41Y8C4oxk4zgJT1KXyQr35UhZcfsp5mP86Z2G7UUzojU',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.vip1]: {
    vaultId: VaultId.vip1,
    name: 'JLP Delta Neutral',
    subname: 'vip1',
    type: VaultType.Drift,
    vaultAddress: 'CZU38L2NyL6tqFxzYAGYkmkf2JG98tZfZ2CnUapVgXQe',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.ethnl]: {
    vaultId: VaultId.ethnl,
    name: 'ETH Super Staking',

    type: VaultType.Drift,
    vaultAddress: 'ENr5e1BMN5vFUHf4iCCPzR4GjWCKgtHnQcdniRQqMdEL',
    depositToken: SupportedToken.WETH,
    pfee: 0.2,
  },
  [VaultId.print]: {
    vaultId: VaultId.print,
    name: 'JLP Traders Print',

    type: VaultType.Drift,
    vaultAddress: '85XuR4kE5yxp1hk91WHAawinXZsuJowxy59STYYpM9pK',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.solbasisinf]: {
    vaultId: VaultId.solbasisinf,
    name: 'Drift funding arb',

    type: VaultType.Drift,
    vaultAddress: 'CxL8eQmGhN9LKSoHj7bU95JekFPtyZoUc57mbehb5A56',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.vip2]: {
    vaultId: VaultId.vip2,
    name: 'JLP Delta Neutral',
    subname: 'vip2',
    type: VaultType.Drift,
    vaultAddress: 'DUW6uWcrsjYmsYDjp9iGDN4JdRa2MqznjuxjKVok5Fsj',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip3]: {
    vaultId: VaultId.vip3,
    name: 'JLP Delta Neutral',
    subname: 'vip3',
    type: VaultType.Drift,
    vaultAddress: 'Fd3k4c6Dv7m9673ae87P6duQrftY9UVfwiCxngNbJrUQ',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.perpsbasket]: {
    vaultId: VaultId.perpsbasket,
    name: 'USDC Basis',
    subname: 'Perps Basket',
    type: VaultType.Drift,
    vaultAddress: '4cvgasNfbJ36yeMVJSkscgL2Yco9dFGdj52Wrg91fmHv',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.vip5]: {
    vaultId: VaultId.vip5,
    name: 'JLP Delta Neutral',
    subname: 'vip5',
    type: VaultType.Drift,
    vaultAddress: '9BMEyctGvajEubk5iCRBnM9fkeTXUhrxaweYq34jZdC8',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip6]: {
    vaultId: VaultId.vip6,
    name: 'JLP Delta Neutral',
    subname: 'vip6',
    type: VaultType.Drift,
    vaultAddress: '6DFDj66PbPoTC16Sh51MJijoTTMYCbMCVC85tnc5UfQ3',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip7]: {
    vaultId: VaultId.vip7,
    name: 'JLP Delta Neutral',
    subname: 'vip7',
    type: VaultType.Drift,
    vaultAddress: 'HTLvAjqc6Wkzh4i4QNLHhQHZAnrtVvkGyYeyCiUWLe9b',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip8]: {
    vaultId: VaultId.vip8,
    name: 'SOL Super Staking',
    subname: 'vip8',
    type: VaultType.Drift,
    vaultAddress: 'CYUyHzu6Z3JyBhfkQpZZwWqa2zpcmzaK1xXS96n8ea1U',
    depositToken: SupportedToken.SOL,
    pfee: 0.2,
  },
  [VaultId.jlpdnv3]: {
    vaultId: VaultId.jlpdnv3,
    name: 'JLP Delta Neutral',
    subname: 'Drift-3',
    type: VaultType.Drift,
    vaultAddress: '7ngzeBygEksaBvKzHEeihqoLpDpWqTNRMVh2wCyb6NP8',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.vip10]: {
    vaultId: VaultId.vip10,
    name: 'USDC Staking',
    subname: 'vip10',
    type: VaultType.Drift,
    vaultAddress: '5Wv7V9zLGD3g7JTXfYjpzFEs42kjowXqUHh7wQ5ryVef',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.vip11]: {
    vaultId: VaultId.vip11,
    name: 'JLP Delta Neutral',
    subname: 'vip11',
    type: VaultType.Drift,
    vaultAddress: 'HhLwXF15V3MTVG9ucGGmT6mcEuqt2BjHuTCJBi4Zvi4K',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip12]: {
    vaultId: VaultId.vip12,
    name: 'JLP Delta Neutral',
    subname: 'vip12',
    type: VaultType.Drift,
    vaultAddress: 'GpMcLVnUqE1RyEB5rRFsFQJGKiPBBXqrpFsdbfUPgbqv',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip13]: {
    vaultId: VaultId.vip13,
    name: 'JLP Delta Neutral',
    subname: 'vip13',
    type: VaultType.Drift,
    vaultAddress: '9V2LggfMo1EjaBbq3qBRBifD287m8zryrZgTR72grcCp',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.solctamarco]: {
    vaultId: VaultId.solctamarco,
    name: 'SOL Momentum',
    subname: 'CTA-Marco',
    type: VaultType.Drift,
    vaultAddress: 'DbAX9qNiHrtrngLz8e5nBNWbmeGGVRKUQtxfGdENCFJS',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.vip14]: {
    vaultId: VaultId.vip14,
    name: 'JLP Delta Neutral',
    subname: 'vip14',
    type: VaultType.Drift,
    vaultAddress: '4iSH214QLwWnJQNwTH6VfH4oNcPccr7HnMmsybjnTtez',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip15]: {
    vaultId: VaultId.vip15,
    name: 'JLP Delta Neutral',
    subname: 'vip15',
    type: VaultType.Drift,
    vaultAddress: 'AwVR9y8Qw5erzrzE8hcs1j1se86yBwmrRidWb1qzaAy2',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip16]: {
    vaultId: VaultId.vip16,
    name: 'JLP Delta Neutral',
    subname: 'vip16',
    type: VaultType.Drift,
    vaultAddress: '4H3wAK5tkT7G1vFrj6J9jWGvbaqVGkzPPBsp9qyKUYz9',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.usdctangem]: {
    vaultId: VaultId.usdctangem,
    name: 'JLP Delta Neutral',
    subname: 'tangem',
    type: VaultType.Drift,
    vaultAddress: 'HS2anXrdps1S2DZCHepgzfcoaqSUWBBuuqTRMugJisP2',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.btctangem]: {
    vaultId: VaultId.btctangem,
    name: 'BTC Super Staking',
    subname: 'tangem',
    type: VaultType.Drift,
    vaultAddress: '6E2sh7ygUzXFJAafXX5sMeSj7eK6YkYqpoAzXm7bYtCw',
    depositToken: SupportedToken.WBTC,
    pfee: 0.2,
  },
  [VaultId.vip17]: {
    vaultId: VaultId.vip17,
    name: 'JLP Delta Neutral',
    subname: 'vip17',
    type: VaultType.Drift,
    vaultAddress: '3UhqS9P4AhKMrCv7yE1LujgQS2xjFnRhANC5dPf2bZem',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip18]: {
    vaultId: VaultId.vip18,
    name: 'JLP Delta Neutral',
    subname: 'vip18',
    type: VaultType.Drift,
    vaultAddress: '1CUvZgVGaxV6sDUjFrWHyzukWBD2amUi3dQkvh9KKVA',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.jlpdnv4]: {
    vaultId: VaultId.jlpdnv4,
    name: 'JLP Delta Neutral',
    subname: 'Drift-4',
    type: VaultType.Drift,
    vaultAddress: '46fQeq1UX5djNkrY5d942inhRHjp1cTZmWBeCUZoqWT3',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.solethflip]: {
    vaultId: VaultId.solethflip,
    name: 'Long SOL, Short ETH',
    subname: 'Solana Flippening',
    type: VaultType.Drift,
    vaultAddress: '2zsHAfvD2BpmZbuPhc32dija8cXu8ow6n2yzyZTMvQ8V',
    depositToken: SupportedToken.USDC,
    pfee: 0.1,
  },
  [VaultId.jlpdnv5]: {
    vaultId: VaultId.jlpdnv5,
    name: 'JLP Delta Neutral',
    subname: 'Drift-5',
    type: VaultType.Drift,
    vaultAddress: '9omhWDzVxpX1vPBxAhJpVao7baoVzZpNib32vozZLxGm',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.vip1ag]: {
    vaultId: VaultId.vip1ag,
    name: 'JLP Delta Neutral',
    subname: 'vip pool 1',
    type: VaultType.Drift,
    vaultAddress: '5FqiXogZCcyZoNeTZzNvywY5s9ZRzNsPPkZ2Q4YRu6ww',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.usdcsuper]: {
    vaultId: VaultId.usdcsuper,
    name: 'JLP Delta Neutral',
    subname: 'Project Super',
    type: VaultType.Drift,
    vaultAddress: '6un71hP7xhpc8nqWWnbYPiamjAckEGH1A6zzenpGdZLf',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.vip19]: {
    vaultId: VaultId.vip19,
    name: 'JLP Delta Neutral',
    subname: 'vip19',
    type: VaultType.Drift,
    vaultAddress: '5DPwSqEfaEsBH4zzZha35TpWRRPnWFfVgYZyK3zNswT7',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip20]: {
    vaultId: VaultId.vip20,
    name: 'JLP Delta Neutral',
    subname: 'vip20',
    type: VaultType.Drift,
    vaultAddress: 'AAiykf4cgdFxz4kyRNuCFf9xFwy7c1gHiWacydmi1jLS',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.neutralizedjlp]: {
    vaultId: VaultId.neutralizedjlp,
    name: 'JLP Delta Neutral',
    subname: 'Neutralized JLP',
    type: VaultType.Drift,
    vaultAddress: 'CG2zv4wsSetgs6mAucEKnHPwSoZSLYMwGroembTUNeaU',
    depositToken: SupportedToken.JLP,
    pfee: 0,
  },
  [VaultId.thebigshort]: {
    vaultId: VaultId.thebigshort,
    name: 'Inverse JLP DN',
    subname: 'The Big Short',
    type: VaultType.Drift,
    vaultAddress: '2csxi2M4uMijHW3CvnHqAYJ9CcLcZbGmDNKSz1qjRAVQ',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.fuelmaxi]: {
    vaultId: VaultId.fuelmaxi,
    name: 'FUEL Maxi',

    type: VaultType.Drift,
    vaultAddress: 'DzaHA2zD7XQhj2Z6tG9YxVtgcvJ4sqzeLYr8dszyQTEq',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.usdcsavings]: {
    vaultId: VaultId.usdcsavings,
    name: 'USDC Savings',
    subname: 'Drawdown Protected',
    type: VaultType.Drift,
    vaultAddress: '4i2L5zvzUM5LXqUYm35Ytv4BGSmnFVTqG5xtFfJesm14',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.solsavings]: {
    vaultId: VaultId.solsavings,
    name: 'SOL Savings',
    subname: 'Drawdown Protected',
    type: VaultType.Drift,
    vaultAddress: 'A6cPV4DrePTUUamBM87MDqK9kBy9vbucjhrCxtxzExK9',
    depositToken: SupportedToken.SOL,
    pfee: 0,
  },
  [VaultId.ethsavings]: {
    vaultId: VaultId.ethsavings,
    name: 'ETH Savings',
    subname: 'Drawdown Protected',
    type: VaultType.Drift,
    vaultAddress: '8JjFwxduSVCY91s2yBVGgKSAKPwPkuTKEchjRw74Du5w',
    depositToken: SupportedToken.WETH,
    pfee: 0,
  },
  [VaultId.btcsavings]: {
    vaultId: VaultId.btcsavings,
    name: 'BTC Savings',
    subname: 'Drawdown Protected',
    type: VaultType.Drift,
    vaultAddress: '494C23vX4h7Bhfyz92hScg71PXn9huG9SqY8mFYhRJoK',
    depositToken: SupportedToken.WBTC,
    pfee: 0,
  },
  [VaultId.jlpdnteam]: {
    vaultId: VaultId.jlpdnteam,
    name: 'JLP Delta Neutral',
    subname: 'vip team',
    type: VaultType.Drift,
    vaultAddress: 'FBYp9toQEqNiGeP8BzyvRD1FUauJBFk5eYUEkgqvigZ5',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.btcdom]: {
    vaultId: VaultId.btcdom,
    name: 'BTC Dominance',

    type: VaultType.Drift,
    vaultAddress: '5BCDLjnQXv92AYySpdEpENgYhABaVf92fym1MYNyhVuo',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.fartdom]: {
    vaultId: VaultId.fartdom,
    name: 'FART Dominance',
    subname: 'Hot Air Rises',
    type: VaultType.Drift,
    vaultAddress: '5cbTtvNVg1qc5L5Fcnz9R3X2QsYTtMCwBZRwBbuoEhn5',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.hyperjlp]: {
    vaultId: VaultId.hyperjlp,
    name: 'Hyper JLP',

    type: VaultType.Drift,
    vaultAddress: 'A1B9MVput3r1jS91iu8ckdDiMSugXbQeEtvJEQsUHsPi',
    depositToken: SupportedToken.USDC,
    pfee: 0.15,
  },
  [VaultId.bonkpump]: {
    vaultId: VaultId.bonkpump,
    name: 'Long BONK, Short PUMP',

    type: VaultType.Drift,
    vaultAddress: '7uUJtfVzhu6aXZypsARsAK8sjWsDxWJYUkaNzm3hTgid',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.nmmjlpdn]: {
    vaultId: VaultId.nmmjlpdn,
    name: 'JLP Delta Neutral',
    subname: 'vip21',
    type: VaultType.Drift,
    vaultAddress: '7qPbUA5HmxjpoxniqoH8r5SZ5dY1hqYXGr8QSZsRXynX',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.memesetf]: {
    vaultId: VaultId.memesetf,
    name: 'Memes ETF',
    subname: 'Generational Wealth',
    type: VaultType.Drift,
    vaultAddress: 'AHfaqTwFhWiX2DZrYbTivBpbrstNJRyjHG4mFPVpJS5n',
    depositToken: SupportedToken.USDC,
    pfee: 0,
  },
  [VaultId.annafromperena]: {
    vaultId: VaultId.annafromperena,
    name: 'JLP Delta Neutral',
    subname: 'Perena',
    type: VaultType.Drift,
    vaultAddress: '9vmBYT7hcjexuHM3iML3buTz3PchvULH5EfAjG12TtRZ',
    depositToken: SupportedToken.USDC,
    pfee: 0.25,
  },
  [VaultId.vip22]: {
    vaultId: VaultId.vip22,
    name: 'JLP Delta Neutral',
    subname: 'vip22',
    type: VaultType.Drift,
    vaultAddress: 'HhhFKvtkbz9v7nDxsFVD8Z3qSY2r9Ncc9rnKopFaGCkb',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.vip23]: {
    vaultId: VaultId.vip23,
    name: 'JLP Delta Neutral',
    subname: 'vip23',
    type: VaultType.Drift,
    vaultAddress: '8oZhUFmrA7p3SkVX7o4nFfSLsmt3KfCyW8grFydtvvuj',
    depositToken: SupportedToken.USDC,
    pfee: 0.1,
  },
  [VaultId.vip24]: {
    vaultId: VaultId.vip24,
    name: 'JLP Delta Neutral',
    subname: 'vip24',
    type: VaultType.Drift,
    vaultAddress: '2Z2YH1RAXS8CNJo3QkYpQ4WHGH9jzNQ5m8YunRkY65mf',
    depositToken: SupportedToken.USDC,
    pfee: 0.2,
  },
  [VaultId.solnlperps]: {
    vaultId: VaultId.solnlperps,
    name: 'SOL Super Staking',
    subname: 'Perps',
    type: VaultType.Drift,
    vaultAddress: 'DiZ2RKDmCxMwPy8tEQzeh6dhKDEB9F5yezyJpEYqQyk9',
    depositToken: SupportedToken.SOL,
    pfee: 0.25,
  },
}
